sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 5.0
servides: docker
before_install:
  - echo "We are in the right folder!"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag financas-api-db:latest $DOCKER_USERNAME/financas-api-db:$TRAVIS_JOB_ID;
    docker tag financas-api:latest $DOCKER_USERNAME/financas-api:$TRAVIS_JOB_ID;
    docker push rms2307/financas-api-db:$TRAVIS_JOB_ID;
    docker push rms2307/financas-api:$TRAVIS_JOB_ID;
  on:
    branch: master
notifications:
  email:
    - rms2307@outlook.com