version: '3.4'

services:
  db:
    image: financas-api-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: financas
    ports:
      - 3308:3306
    networks:
      - financas-network

  financas-api:
    image: financas-api
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    depends_on:
      - db
    networks:
      - financas-network
networks:
    financas-network:
      driver: bridge
