insert into custofixodescricao (`UserId`, `Desc`) values (3, 'vel accumsan');
insert into custofixodescricao (`UserId`, `Desc`) values (3, 'sapien sapien');
insert into custofixodescricao (`UserId`, `Desc`) values (3, 'at ipsum');
insert into custofixodescricao (`UserId`, `Desc`) values (3, 'convallis');
insert into custofixodescricao (`UserId`, `Desc`) values (3, 'in');
insert into custofixodescricao (`UserId`, `Desc`) values (3, 'suscipit');
insert into custofixodescricao (`UserId`, `Desc`) values (3, 'ultrices');
insert into custofixodescricao (`UserId`, `Desc`) values (3, 'scelerisque');
insert into custofixodescricao (`UserId`, `Desc`) values (3, 'sapien quis');
insert into custofixodescricao (`UserId`, `Desc`) values (3, 'interdum');